# Generated by Django 3.0 on 2019-12-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_book', models.IntegerField(blank=True, null=True, verbose_name='Número de habitación')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Fecha de entrada')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('days', models.IntegerField(verbose_name='Días')),
                ('n_persons', models.IntegerField(verbose_name='Número de personas')),
                ('total_price', models.IntegerField(verbose_name='Precio Total')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('name_of_card', models.CharField(max_length=50, verbose_name='Nombre de la tarjeta')),
                ('credit_card_number', models.IntegerField(verbose_name='Número de tarjeta')),
                ('State', models.CharField(blank=True, choices=[('Confirmada', 'Confirmada'), ('Checkin', 'Checkin'), ('Checkout', 'Checkout')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('locator', models.CharField(blank=True, max_length=32, null=True, verbose_name='Localizador')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
