# Generated by Django 3.0 on 2019-12-16 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20191216_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='user_email',
            field=models.EmailField(default=datetime.datetime(2019, 12, 16, 10, 25, 48, 456461, tzinfo=utc), max_length=254, verbose_name='Correo electrónico del usuario'),
            preserve_default=False,
        ),
    ]
