# Generated by Django 3.0 on 2019-12-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name_room', models.CharField(max_length=50, verbose_name='Nombre de la habitación')),
                ('room_type', models.CharField(choices=[('1', 'Individual'), ('2', 'Doble'), ('3', 'Triple'), ('4', 'Cuadruple')], max_length=1, verbose_name='Tipo')),
                ('number_room', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Habitación')),
                ('price_room', models.IntegerField(verbose_name='Precio')),
                ('image', models.ImageField(upload_to='rooms', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['number_room'],
            },
        ),
    ]
